remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: false
 temporary: true
 internship: false
 other: true
 volunteer: false

date:
 all time: false
 month: true
 week: true
 24 hours: true

positions:
  - Software Developer in Test
  - Software Developer Engineer in Test
  - Test Automation Engineer
  - QA Automation Engineer
  - QA Automation Developer
  - Quality Developer
  - Quality Engineer

locations:
  - Canada

distance: 100

companyBlacklist:

titleBlacklist:
